FROM msopenstack/sentinel-ubuntu:latest
 
RUN apt-get update -y
RUN apt-get install software-properties-common -y
RUN puppet module install puppetlabs-stdlib
RUN puppet module install puppetlabs-mysql
RUN puppet module install saz-php

RUN git clone https://github.com/openstack-hyper-v/puppet-osticket /etc/puppet/modules/osticket
RUN puppet apply --debug --trace --verbose --modulepath=/etc/puppet/modules /etc/puppet/modules/osticket/tests/init.pp
